#!/bin/sh

# run linter before commits
npm run lint 

if [ $? -eq 0 ]
then

  echo "✨✨✨✨✨✨✨✨✨✨✨✨✨"
  echo "    Linter looks good"
  echo "✨✨✨✨✨✨✨✨✨✨✨✨✨"
  exit 0
else

  echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
  echo "  Sorry bro, you'll have to check the linter errros above" >&2
  echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
  exit 1
fi
